crud/urls.py
from django.contrib import admin
from django.urls import path
from App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 
    path('create/',views.Create.as_view(),name="create"),
    
    path('',views.Read.as_view(),name="read"),
   
    path('update/<int:pk>',views.Update.as_view(),name="update"),
    
    path('delete/<int:pk>',views.Delete.as_view(),name="delete"),
]

App/models.py
from django.db import models

# Create your models here.
# Table Candidate (No Foreing key)

GENDER=(
    ('M','M'),
    ('F','F')
)

CAREER=(
    ('FrontEnd','FrontEnd'),
    ('Bkackebd','Bkackebd'),
    ('Fullstack','Fullstack'),
    ('Intern','Intern')
)
class Candidate(models.Model):
    name = models.CharField( max_length=100)
    phone = models.CharField( max_length=25)
    email = models.CharField( max_length=100)
    gender = models.CharField( max_length=1 , null=True ,choices=GENDER)
    career = models.CharField( max_length=50,null=True ,choices=CAREER)
    
    def __str__(self):
        return self.name
    
    

App/forms.py
from django import forms
from App.models import Candidate


class CandidateForm(forms.ModelForm):
    class Meta:
        model= Candidate
        fields ="__all__"
        

App/views.py
from App.models import Candidate
from django.views.generic import ListView, CreateView, UpdateView,DeleteView
from django.urls import reverse_lazy


#CreaTE
class Create (CreateView):
    model= Candidate
    fields='__all__'
    success_url=reverse_lazy('read')

# Read

class Read (ListView):
    model=Candidate
    queryset=Candidate.objects.all()


class Update(UpdateView):
    model = Candidate
    fields='__all__'
    success_url=reverse_lazy('read')
    

class Delete(DeleteView):
    queryset=Candidate.objects.all()
    success_url=reverse_lazy('read')
    


#Update



#DElete 

App/templates/App/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Fontr  Awesonwe -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Favicom -->
    <link rel="shortcut icon" href={%  static "img/favicon.ico" %}>
    <!-- logo -->
    <link rel="shortcut icon" href={%  static "img/logo.ico" %}>
    <!-- static csssss -->
    <link rel="stylesheet" href={%  static "css/style.css" %}>
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <!-- Block content (Root) -->
        <!-- NAvbart -->
        <div class="header">
            <nav class="navbar navbar-expand-lg navbar-dark navbar {% block navbar %}{% endblock navbar %}">
                <a class="navbar-brand flex-grow-1 text-center ">
                    
                    {% block nav-content %}
                        <i class="fas fa-user-friends" >  </i>  &nbsp;&nbsp; Lista de Candidatos          
                    {% endblock nav-content %}
                        
                   
                 </a>
            </nav>
        </div>

        {% block content %}{% endblock content %}
            
        <!--  -->
    </div>
    <!-- Footer -->
    <footer class="bg-dark text-center text-lg-start" id="footer" style="color:#fff">
        <div class="text-center p-3" style="background-color:rgba(0,0,0,0.2) ">
            &copy; {% now "y" %} Copyright:
            <a class="text-light" style="text-decoration:none;">

                <span  {% block footer %} style="color: #89cff0;" {% endblock footer %}> 
                   www.esteesmisitioweb.com
                </span>
            </a>
        </div>
    </footer>

    <!-- bootstrap 5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

App/templates/App/candidate_confirm_delete.html
{% extends 'App/candidate_list.html' %}



{% block navbar %}
    bg-danger
{% endblock navbar %}
    
<!-- Navar Content -->

{% block nav-content %}
  <i class="fas fa-user-times"></i>&nbsp;&nbsp; Delete Candidate
{% endblock nav-content %}


<!-- Footer -->


{% block footer %}
    style="color:#ff7f7f;"
{% endblock footer %}
    



<!-- Page content -->


{% block content %}
    <br>
    <div class="container mt-5" style="width:450px">
        <div class="card p-3 border-dark">
            <h6 class="modal-title">
                <i class="fas fa-trash-alt"></i> &nbsp;&nbsp; Delete Candidate
            </h6>
            <hr>
            <div class="text-center text-danger"> <i class="far fa-times-circle fa-5x mb-4 mt-2"></i> </div>
            <div class="text-center text-danger">
                <span>Esta seguro de eliminar este candidato</span>
                <div class="text-dark mt-3 mb-2">CAndidate: <strong>{{candidate.name}}</strong></div>
            </div>
            <hr>
            <form method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger btn-sm ms-2" type="submit" value="Delete" style ="float:right;">
                <a href="{% url 'read' %}" class="btn btn-secondary btn-sm" style="float:right;">Cancel</a>
            </form>
        </div>
        <br><hr><br>
        <span>
            If you  Proced , no podra ser recuperado
        </span>
    </div>
{% endblock content %}
    

App/templates/App/candidate_form.html
{% extends 'App/candidate_list.html' %}


<!-- Load Criyspi form -->
{% load crispy_forms_tags %}


{% block nav-content %}
  <i class="fas fa-user-check"></i>&nbsp;&nbsp; CANDIDATE
{% endblock nav-content %}
    
<!-- Page Contentent -->

{% block content %}
    <div class="container mt-5" style="width:450px">
        <div class="card p-3 border-dark">
            <form method="POST" autocomplete="off">
                {% csrf_token %}
                {{ form.name|as_crispy_field }}
                {{ form.phone|as_crispy_field }}
                {{ form.email|as_crispy_field }}
                {{ form.gender|as_crispy_field }}
                {{ form.career|as_crispy_field }}
                <br><hr>
                <div class="d-grid gap-2 mb-3">
                    <button  type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{% url 'read' %}" class="btn btn-secondary">Cancel</a>
                </div>
                <hr>
            </form>
        </div>
    </div>
{% endblock content %}
    

App/templates/App/candidate_list.html
{% extends 'App/base.html' %}

<!-- Contenidko de la pagina -->

{% block content %}
    <div class="container">
        <a href="{% url 'create' %}" class="btn btn-outline-primary mb-3 mt-5">
            <i class="fas fa-plus">&nbsp;&nbsp;Candidate</i>
        </a>
    </div>
    <table class="table table-bordered" style="text-align:center; font: size 14px; ">
        <thead class="table-primary">
            <tr>
                <th style="width: 25%;">Name</th>
                <th style="width: 20%;">Phone</th>
                <th style="width: 23%;">Email</th>
                <th style="width: 7%;">Gernder</th>
                <th style="width: 15%;">Careeer</th>
                <th colspan="2" style="width: 10%;">Actions</th>
            </tr>
        </thead>
        <!--  DAta form db -->
     
     {% for candidate in object_list %}
           
               <tr>
                    <td>{{candidate.name}}</td>
                    <td>{{candidate.phone}}</td>
                    <td>{{candidate.email}}</td>
                    <td>{{candidate.gender}}</td>
                    <td>{{candidate.career}}</td>
                    <td>
                        <a href="{% url 'update' pk=candidate.id %}" class="btn btn-primary btn-sm" style="width:45px ;">
                            <i class="fas fa-pen"></i>
                        </a>
                        
                    </td>
                    <td>
                        <a href="{% url 'delete' pk=candidate.id %}" class="btn btn-secondary btn-sm" style="width:45px ;">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        
                    </td>
               </tr>
           
     {% endfor %}
        
    </table>
    
{% endblock content %}
    